### ISSUE TITLE
A few pointers

### ISSUE THREAD

**Issue by xzjkya** [lincolwn/python-strava#13]
As I promised. Since I'm not actively developing this with you. I might as well point out some improvements. You might pin this issue so we don't several issues for improvements.

- In `constants.py` you don't have to do that (unless you're targeting older python versions, but why?). Python already has support for enums. And they seem to have what you need and have more fluffies to it. https://docs.python.org/3.6/library/enum.html
- In `exceptions.py` line 6, there's a typo. It's **Unknown** not **Unkown**
- In `exceptions.py` line 10, you're not exactly using self.response for anything useful. Maybe get rid of it? 
- In `client.py`, every single method that deals with strava directly seems to have `path` and `return self._dispatcher(...)` declared. Might as well factor that out in a `@path` decorator with a possible `batch_iterator` option? A helper decorator. Each would only do whats necessary to wrap up, transform, etc. That's an idea though.

**Comment by lincolwn** [comment]
Thanks for taking a look at this project. Regarding those points, I can say:
1. I intentionally avoid using `enums` because I want a particular behavior of those objects. I want a similar dict behavior when we can iterate by `values` use `in` operator, etc.
2. Good call out. Thanks!
3. I'm just attaching the Strava HTTP response into the exception for debug reasons when the handler catch this one.
4. It looks a good idea. We can discuss more about its detail.
